all:
	/usr/bin/gcc -O3 -march=native -fomit-frame-pointer -o train_accu_900 cbd.c fips202.c indcpa.c kem.c ntt.c poly.c polyvec.c train_accu_900.c reduce.c rng.c verify.c symmetric-shake.c -lcrypto
	/usr/bin/gcc -O3 -march=native -fomit-frame-pointer -o train_accu_950 cbd.c fips202.c indcpa.c kem.c ntt.c poly.c polyvec.c train_accu_950.c reduce.c rng.c verify.c symmetric-shake.c -lcrypto
	/usr/bin/gcc -O3 -march=native -fomit-frame-pointer -o train_accu_960 cbd.c fips202.c indcpa.c kem.c ntt.c poly.c polyvec.c train_accu_960.c reduce.c rng.c verify.c symmetric-shake.c -lcrypto
